apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: featureflags.featurecontroller.featured.io
spec:
  group: featurecontroller.featured.io
  version: v1alpha1
  names:
    kind: FeatureFlag
    plural: featureflags
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10
